# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Flippidy Bits"
description: > # this means to ignore newlines until "email:"
   Exploration of computer science, machine learning, mathematics, and more from a perspective of learning and sharing knowledge.

email: aaronsmith1101@gmail.com
#blog logo
logo: "/assets/images/fb_logo.png"
logo_large: "/assets/images/fb_logo_full.png"
float_logo: true # true, false (default)

# blog cover
cover: ""

name: Aaron Smith
author: 'Aaron Smith'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.flippidybits.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@flippidybits'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-41228204-1

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/flippidybits
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/aaronleesmith
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

  - icon: linkedin
    url: https://www.linkedin.com/in/aaron-smith-28aa8657/
    desc: Find me on LinkedIn